import { defineCategories } from '../../lib/helpers/category/listingCategory.builders';
import { CATEGORY_ICONS } from '../../utils/icons';
import {
  BOAT_ENGINES_FOR_SALE_SUBCATEGORIES,
  BOAT_PARTS_SUBCATEGORIES,
  BOATS_FOR_RENT_SUBCATEGORIES,
  BOATS_FOR_SALE_SUBCATEGORIES,
  CAR_PARTS_SUBCATEGORIES,
  CARS_BUSES_SUBCATEGORIES,
  CARS_ELECTRIC_CARS_SUBCATEGORIES,
  CARS_FOR_SALE_SUBCATEGORIES,
  CARS_LEASE_CARS_SUBCATEGORIES,
  CARS_TRAILERS_SUBCATEGORIES,
  CARS_TRUCK_SUBCATEGORIES,
  FARM_EQUIPMENT_FERTILIZER_SPREADER_SUBCATEGORIES,
  FARM_EQUIPMENT_HARVESTER_SUBCATEGORIES,
  FARM_EQUIPMENT_IRRIGATION_SUBCATEGORIES,
  FARM_EQUIPMENT_PLOW_SUBCATEGORIES,
  FARM_EQUIPMENT_TOOLS_SUBCATEGORIES,
  FARM_EQUIPMENT_TRACTOR_SUBCATEGORIES,
  MARKETPLACE_ANIMAL_AND_SUPPLIES_SUBCATEGORIES,
  MARKETPLACE_ANTIQUES_SUBCATEGORIES,
  MARKETPLACE_EDUCATION_SUBCATEGORIES,
  MARKETPLACE_ELECTRONICS_SUBCATEGORIES,
  MARKETPLACE_FASHION_SUBCATEGORIES,
  MARKETPLACE_FURNITURE_SUBCATEGORIES,
  MARKETPLACE_SPORTS_AND_OUTDOORS_SUBCATEGORIES,
  MOTORCYCLES_FOR_RENT_SUBCATEGORIES,
  MOTORCYCLES_FOR_SALE_SUBCATEGORIES,
  MOTORCYCLES_OTHER_SUBCATEGORIES,
  MOTORCYCLES_SPARE_PARTS_SUBCATEGORIES,
  REAL_ESTATE_COMMERCIAL_SUBCATEGORIES,
  REAL_ESTATE_FARM_FOR_SALE_SUBCATEGORIES,
  REAL_ESTATE_FOR_RENT_SUBCATEGORIES,
  REAL_ESTATE_FOR_SALE_SUBCATEGORIES,
  REAL_ESTATE_LAND_FOR_SALE_SUBCATEGORIES,
} from '../sub-categories/subCategories';

export const MARKETPLACE_CATEGORIES = defineCategories([
  {
    key: 'antiques',
    name: 'Antiques & Art',
    icon: CATEGORY_ICONS.marketplace.antiques,
    feeField: 'art',
    subCategories: MARKETPLACE_ANTIQUES_SUBCATEGORIES,
  },
  {
    key: 'electronics',
    name: 'Electronics',
    icon: CATEGORY_ICONS.marketplace.electronics,
    feeField: 'electronics',
    subCategories: MARKETPLACE_ELECTRONICS_SUBCATEGORIES,
  },
  {
    key: 'animalAndSupplies',
    name: 'Animals & Supplies',
    icon: CATEGORY_ICONS.marketplace.animalAndSupplies,
    feeField: 'animal',
    subCategories: MARKETPLACE_ANIMAL_AND_SUPPLIES_SUBCATEGORIES,
  },
  {
    key: 'sportsAndOutdoors',
    name: 'Sports & Outdoors',
    icon: CATEGORY_ICONS.marketplace.sportsAndOutdoors,
    feeField: 'sports',
    subCategories: MARKETPLACE_SPORTS_AND_OUTDOORS_SUBCATEGORIES,
  },
  {
    key: 'furniture',
    name: 'Furniture',
    icon: CATEGORY_ICONS.marketplace.furniture,
    feeField: 'furniture',
    subCategories: MARKETPLACE_FURNITURE_SUBCATEGORIES,
  },
  {
    key: 'fashion',
    name: 'Fashion',
    icon: CATEGORY_ICONS.marketplace.fashion,
    feeField: 'fashion',
    subCategories: MARKETPLACE_FASHION_SUBCATEGORIES,
  },
  {
    key: 'education',
    name: 'Education',
    icon: CATEGORY_ICONS.marketplace.education,
    feeField: 'other',
    subCategories: MARKETPLACE_EDUCATION_SUBCATEGORIES,
  },
]);

export const REAL_ESTATE_CATEGORIES = defineCategories([
  {
    key: 'forRent',
    name: 'For Rent',
    icon: CATEGORY_ICONS.realEstate.forRent,
    feeField: 'rent',
    subCategories: REAL_ESTATE_FOR_RENT_SUBCATEGORIES,
  },
  {
    key: 'forSale',
    name: 'For Sale',
    icon: CATEGORY_ICONS.realEstate.forSale,
    feeField: 'sale',
    subCategories: REAL_ESTATE_FOR_SALE_SUBCATEGORIES,
  },
  {
    key: 'landForSale',
    name: 'Land For Sale',
    icon: CATEGORY_ICONS.realEstate.landForSale,
    feeField: 'land',
    subCategories: REAL_ESTATE_LAND_FOR_SALE_SUBCATEGORIES,
  },
  {
    key: 'farmForSale',
    name: 'Farms For Sale',
    icon: CATEGORY_ICONS.realEstate.farmForSale,
    feeField: 'farm',
    subCategories: REAL_ESTATE_FARM_FOR_SALE_SUBCATEGORIES,
  },
  {
    key: 'commercial',
    name: 'Commercial',
    icon: CATEGORY_ICONS.realEstate.commercial,
    feeField: 'business',
    subCategories: REAL_ESTATE_COMMERCIAL_SUBCATEGORIES,
  },
]);

export const CARS_CATEGORIES = defineCategories([
  {
    key: 'carsForSale',
    name: 'Cars For Sale',
    icon: CATEGORY_ICONS.cars.carsForSale,
    feeField: 'carSale',
    subCategories: CARS_FOR_SALE_SUBCATEGORIES,
  },
  {
    key: 'leaseCars',
    name: 'Lease Cars',
    icon: CATEGORY_ICONS.cars.leaseCars,
    feeField: 'carRent',
    subCategories: CARS_LEASE_CARS_SUBCATEGORIES,
  },
  {
    key: 'trailers',
    name: 'Trailers',
    icon: CATEGORY_ICONS.cars.trailers,
    feeField: 'trailer',
    subCategories: CARS_TRAILERS_SUBCATEGORIES,
  },
  {
    key: 'carParts',
    name: 'Car Parts',
    icon: CATEGORY_ICONS.cars.carParts,
    feeField: 'carParts',
    subCategories: CAR_PARTS_SUBCATEGORIES,
  },
  {
    key: 'truck',
    name: 'Trucks',
    icon: CATEGORY_ICONS.cars.truck,
    feeField: 'truck',
    subCategories: CARS_TRUCK_SUBCATEGORIES,
  },
  {
    key: 'electricCars',
    name: 'Electric Cars',
    icon: CATEGORY_ICONS.cars.electricCars,
    feeField: 'electricCar',
    subCategories: CARS_ELECTRIC_CARS_SUBCATEGORIES,
  },
  {
    key: 'buses',
    name: 'Buses',
    icon: CATEGORY_ICONS.cars.buses,
    feeField: 'carSale',
    subCategories: CARS_BUSES_SUBCATEGORIES,
  },
]);

export const MOTORCYCLES_CATEGORIES = defineCategories([
  {
    key: 'forSale',
    name: 'For Sale',
    icon: CATEGORY_ICONS.motorcycles.forSale,
    feeField: 'motoSale',
    subCategories: MOTORCYCLES_FOR_SALE_SUBCATEGORIES,
  },
  {
    key: 'forRent',
    name: 'For Rent',
    icon: CATEGORY_ICONS.motorcycles.forRent,
    feeField: 'motoRent',
    subCategories: MOTORCYCLES_FOR_RENT_SUBCATEGORIES,
  },
  {
    key: 'spareParts',
    name: 'Spare Parts',
    icon: CATEGORY_ICONS.motorcycles.spareParts,
    feeField: 'motoParts',
    subCategories: MOTORCYCLES_SPARE_PARTS_SUBCATEGORIES,
  },
  {
    key: 'other',
    name: 'Other',
    icon: CATEGORY_ICONS.motorcycles.other,
    feeField: 'other',
    subCategories: MOTORCYCLES_OTHER_SUBCATEGORIES,
  },
]);

export const BOATS_CATEGORIES = defineCategories([
  {
    key: 'boatsForSale',
    name: 'Boats For Sale',
    icon: CATEGORY_ICONS.boats.boatsForSale,
    feeField: 'boatSale',
    subCategories: BOATS_FOR_SALE_SUBCATEGORIES,
  },
  {
    key: 'boatsForRent',
    name: 'Boats For Rent',
    icon: CATEGORY_ICONS.boats.boatsForRent,
    feeField: 'boatRent',
    subCategories: BOATS_FOR_RENT_SUBCATEGORIES,
  },
  {
    key: 'boatEnginesForSale',
    name: 'Boat Engines',
    icon: CATEGORY_ICONS.boats.boatEnginesForSale,
    feeField: 'boatEngine',
    subCategories: BOAT_ENGINES_FOR_SALE_SUBCATEGORIES,
  },
  {
    key: 'boatParts',
    name: 'Boat Parts',
    icon: CATEGORY_ICONS.boats.boatParts,
    feeField: 'boatParts',
    subCategories: BOAT_PARTS_SUBCATEGORIES,
  },
]);

export const FARM_EQUIPMENT_CATEGORIES = defineCategories([
  {
    key: 'tractor',
    name: 'Tractors',
    icon: CATEGORY_ICONS.farmEquipment.tractor,
    feeField: 'tractorSale',
    subCategories: FARM_EQUIPMENT_TRACTOR_SUBCATEGORIES,
  },
  {
    key: 'tools',
    name: 'Farm Tools',
    icon: CATEGORY_ICONS.farmEquipment.tools,
    feeField: 'agriTool',
    subCategories: FARM_EQUIPMENT_TOOLS_SUBCATEGORIES,
  },
  {
    key: 'fertilizerSpreader',
    name: 'Fertilizer Spreaders',
    icon: CATEGORY_ICONS.farmEquipment.fertilizerSpreader,
    feeField: 'other',
    subCategories: FARM_EQUIPMENT_FERTILIZER_SPREADER_SUBCATEGORIES,
  },
  {
    key: 'harvester',
    name: 'Grain Harvesters',
    icon: CATEGORY_ICONS.farmEquipment.harvester,
    feeField: 'harvester',
    subCategories: FARM_EQUIPMENT_HARVESTER_SUBCATEGORIES,
  },
  {
    key: 'plow',
    name: 'Plows',
    icon: CATEGORY_ICONS.farmEquipment.plow,
    feeField: 'other',
    subCategories: FARM_EQUIPMENT_PLOW_SUBCATEGORIES,
  },
  {
    key: 'irrigation',
    name: 'Irrigation Systems',
    icon: CATEGORY_ICONS.farmEquipment.irrigation,
    feeField: 'other',
    subCategories: FARM_EQUIPMENT_IRRIGATION_SUBCATEGORIES,
  },
]);
