import { StyleSheet } from 'react-native';
import type { ColorPalette } from '../../../components/hooks/useTheme';
import { shadow } from '../../helpers/shadow';

export function createStyles(Colors: ColorPalette, width = 390) {
  const IMG_H = Math.round((width - 32) * 0.56);
  return StyleSheet.create({
    wrap: { marginBottom: 20 },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: Colors.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: Colors.border,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 10,
    },
    headerIconWrap: {
      width: 30,
      height: 30,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: Colors.primary,
    },
    headerTitle: {
      fontSize: 13,
      fontWeight: '800',
      color: Colors.textPrimary,
    },
    headerSub: {
      fontSize: 11,
      color: Colors.textMuted,
      marginTop: 1,
    },
    imgBox: { borderRadius: 18, overflow: 'hidden', marginBottom: 14, height: IMG_H },
    img: { width: '100%', height: '100%' },
    arrow: {
      position: 'absolute', top: '50%', marginTop: -18,
      width: 36, height: 36, borderRadius: 18,
      backgroundColor: Colors.shadow45, alignItems: 'center', justifyContent: 'center',
    },
    arrowL: { left: 8 }, arrowR: { right: 8 },
    dots: { position: 'absolute', bottom: 8, left: 0, right: 0, flexDirection: 'row', justifyContent: 'center', gap: 5 },
    dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: Colors.whiteAlpha50 },
    dotActive: { backgroundColor: Colors.white, width: 16 },
    emptyImage: {
      height: IMG_H,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: Colors.border,
      backgroundColor: Colors.gray50,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 14,
      gap: 8,
    },
    emptyImageIcon: {
      width: 44,
      height: 44,
      borderRadius: 14,
      backgroundColor: Colors.gray100,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyImageText: {
      fontSize: 12,
      color: Colors.textMuted,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    card: {
      backgroundColor: Colors.card, borderRadius: 22, overflow: 'hidden',
      ...shadow({ color: Colors.shadow, offset: { width: 0, height: 6 }, opacity: 0.06, radius: 16, elevation: 3 }),
    },
    titleSection: { padding: 18, borderBottomWidth: 1.5, borderStyle: 'dashed', borderBottomColor: Colors.gray200 },
    listingTitle: { fontSize: 18, fontWeight: '800', color: Colors.textPrimary, marginBottom: 10 },
    chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
    chip: {
      flexDirection: 'row', alignItems: 'center', gap: 4,
      backgroundColor: Colors.primaryGhost, borderRadius: 20,
      paddingHorizontal: 8, paddingVertical: 4,
    },
    chipText: { fontSize: 11, fontWeight: '700', color: Colors.primary },
    chipTextMuted: { color: Colors.textMuted },
    attrsGrid: {
      flexDirection: 'row', flexWrap: 'wrap', gap: 8,
      padding: 18, borderBottomWidth: 1.5, borderStyle: 'dashed', borderBottomColor: Colors.gray200,
    },
    attrCell: {
      backgroundColor: Colors.gray50, borderRadius: 12,
      paddingHorizontal: 10, paddingVertical: 9, minWidth: '28%', flex: 1,
    },
    attrLabel: { fontSize: 9, fontWeight: '800', color: Colors.textMuted, letterSpacing: 0.8, textTransform: 'uppercase', marginBottom: 2 },
    attrValue: { fontSize: 13, fontWeight: '700', color: Colors.textPrimary },
    descBox: { padding: 18, borderBottomWidth: 1.5, borderStyle: 'dashed', borderBottomColor: Colors.gray200 },
    descLabel: { fontSize: 9, fontWeight: '800', color: Colors.textMuted, letterSpacing: 0.8, textTransform: 'uppercase', marginBottom: 4 },
    descText: { fontSize: 13, color: Colors.textSecondary, lineHeight: 18 },
    divider: { borderBottomWidth: 1.5, borderStyle: 'dashed', borderBottomColor: Colors.gray200 },
    breakdown: { padding: 18 },
    breakdownLabel: { fontSize: 10, fontWeight: '800', color: Colors.textMuted, letterSpacing: 1.5, textTransform: 'uppercase', marginBottom: 12 },
    bRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: Colors.gray50, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, marginBottom: 8 },
    planBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
    bKey: { fontSize: 13, color: Colors.textSecondary, fontWeight: '600' },
    bDays: { fontSize: 12, color: Colors.textMuted },
    bVal: { fontSize: 13, fontWeight: '700', color: Colors.textPrimary },
    green: { color: Colors.successDark },
    totalBox: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 12,
      margin: 14,
      marginTop: 4,
      borderRadius: 14,
      borderWidth: 1,
    },
    totalBoxFree: { backgroundColor: Colors.success + '15' },
    totalBoxPaid: { backgroundColor: Colors.primaryGhost, borderColor: Colors.blueTint },
    totalLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    totalLabel: { fontSize: 14, fontWeight: '800' },
    totalLabelPaid: { color: Colors.primary },
    totalAmt: { fontSize: 22, fontWeight: '900' },
    totalAmtPaid: { color: Colors.primary },
    textWhite: { color: Colors.white },
  });
}
