import { Dimensions, Platform, StatusBar, StyleSheet } from 'react-native';
import type { ColorPalette } from '../../../hooks/useTheme';

const { width, height: H } = Dimensions.get('window');
const STATUSBAR_H = Platform.OS === 'android' ? (StatusBar.currentHeight ?? 24) : 0;
const SHEET_TOP = STATUSBAR_H + 48;

export const SHEET_H = H - SHEET_TOP;
export const FAB_SIZE = 56;

export function createStyles(Colors: ColorPalette) {
  return StyleSheet.create({
    sheet: {
      position: 'absolute',
      left: 0,
      right: 0,
      height: SHEET_H,
      backgroundColor: Colors.card,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      zIndex: 99,
      shadowColor: Colors.shadow,
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.18,
      shadowRadius: 16,
      elevation: 20,
      overflow: 'hidden',
    },
    handleBar: {
      backgroundColor: Colors.hage,
      paddingTop: 10,
      paddingBottom: 14,
      paddingHorizontal: 16,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
    },
    handle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: Colors.whiteAlpha35,
      alignSelf: 'center',
      marginBottom: 12,
    },
    sheetHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    sheetTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    sheetTitle: { fontSize: 17, fontWeight: '700', color: Colors.white },
    sheetActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    headerBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: Colors.whiteAlpha15,
    },
    messageList: { padding: 16, gap: 10 },
    emptyWrap: { alignItems: 'center', justifyContent: 'center', paddingVertical: 64, gap: 12 },
    emptyText: { fontSize: 14, color: Colors.textMuted, textAlign: 'center' },
    bubble: {
      maxWidth: '80%',
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 18,
    },
    bubbleAI: {
      alignSelf: 'flex-start',
      backgroundColor: Colors.gray100,
      borderBottomLeftRadius: 4,
    },
    bubbleUser: {
      alignSelf: 'flex-end',
      backgroundColor: Colors.primary,
      borderBottomRightRadius: 4,
    },
    bubbleText: { fontSize: 15, color: Colors.textPrimary, lineHeight: 22 },
    bubbleTextUser: { color: Colors.white },
    bubbleLink: { color: Colors.primary, fontWeight: '700', textDecorationLine: 'underline' },
    listingsWrap: {
      marginTop: 6,
      marginLeft: 4,
      gap: 6,
    },
    chip: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: Colors.card,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: Colors.gray200,
      overflow: 'hidden',
      maxWidth: '85%',
      gap: 8,
    },
    chipImg: {
      width: 56,
      height: 56,
    },
    chipImgPlaceholder: {
      backgroundColor: Colors.gray100,
      alignItems: 'center',
      justifyContent: 'center',
    },
    chipInfo: {
      flex: 1,
      paddingVertical: 8,
      gap: 2,
    },
    chipTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: Colors.textPrimary,
      lineHeight: 18,
    },
    chipPrice: {
      fontSize: 12,
      color: Colors.primary,
      fontWeight: '700',
    },
    thinkingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 8,
    },
    thinkingDots: { flexDirection: 'row', gap: 4 },
    dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: Colors.primary },
    thinkingText: { fontSize: 13, color: Colors.textMuted, fontStyle: 'italic' },
    inputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 14,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: Colors.border,
      backgroundColor: Colors.card,
    },
    input: {
      flex: 1,
      backgroundColor: Colors.surface,
      borderRadius: 24,
      paddingHorizontal: 16,
      paddingVertical: 10,
      fontSize: 15,
      color: Colors.textPrimary,
      borderWidth: 1,
      borderColor: Colors.border,
      maxHeight: 100,
    },
    sendBtn: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: Colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sendBtnDisabled: { backgroundColor: Colors.gray200 },
    fabWrap: {
      position: 'absolute',
      zIndex: 100,
    },
    fab: {
      width: FAB_SIZE,
      height: FAB_SIZE,
      borderRadius: FAB_SIZE / 2,
      backgroundColor: Colors.hage,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: Colors.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
    },
  });
}
