import { StyleSheet } from "react-native";
import type { ColorPalette } from "../../../hooks/useTheme";

export function createStyles(Colors: ColorPalette) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: Colors.background },
    errorWrap: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 12,
      padding: 24,
    },
    errorTitle: { fontSize: 17, color: Colors.textSecondary, fontWeight: "600" },
    errorBack: {
      backgroundColor: Colors.primary,
      borderRadius: 12,
      paddingHorizontal: 24,
      paddingVertical: 12,
      marginTop: 8,
    },
    errorBackText: { color: Colors.white, fontWeight: "700", fontSize: 14 },
    hero: {
      backgroundColor: Colors.card,
      alignItems: "center",
      padding: 24,
      gap: 6,
      borderBottomWidth: 1,
      borderBottomColor: Colors.border,
    },
    logo: {
      width: 88,
      height: 88,
      borderRadius: 20,
      backgroundColor: Colors.border,
      marginBottom: 6,
    },
    nameRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    name: {
      fontSize: 22,
      fontWeight: "800",
      color: Colors.text,
      textAlign: "center",
    },
    typeBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      backgroundColor: Colors.primary + "18",
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingVertical: 5,
    },
    typeText: { fontSize: 12, fontWeight: "700", color: Colors.primary },
    locRow: { flexDirection: "row", alignItems: "center", gap: 4 },
    locText: { fontSize: 13, color: Colors.textMuted },
    section: { backgroundColor: Colors.card, marginTop: 8, padding: 16 },
    sectionTitle: {
      fontSize: 14,
      fontWeight: "700",
      color: Colors.textSecondary,
      textTransform: "uppercase",
      letterSpacing: 0.8,
      marginBottom: 12,
    },
    desc: { fontSize: 15, color: Colors.text, lineHeight: 22 },
    categoryGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
    categoryItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      width: "47%",
      backgroundColor: Colors.primary + "10",
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: Colors.primary + "20",
    },
    categoryLabel: { fontSize: 13, fontWeight: "600", color: Colors.text, flexShrink: 1 },
    photoRow: { gap: 10 },
    photo: {
      width: 130,
      height: 96,
      borderRadius: 12,
      backgroundColor: Colors.border,
    },
    socialGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
    socialBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: Colors.primary + "10",
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingVertical: 9,
      borderWidth: 1,
      borderColor: Colors.primary + "30",
    },
    socialLabel: { fontSize: 13, fontWeight: "600", color: Colors.primary },
    flexFull: { flex: 1 },
    bottomSpacer: { height: 24 },
  });
}
