import { StyleSheet } from 'react-native';
import type { ColorPalette } from '../../../hooks/useTheme';

export function createStyles(Colors: ColorPalette) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: Colors.background },
    center: { flex: 1, justifyContent: 'center' },
    content: { padding: 16, paddingBottom: 32 },
    loadingBox: { paddingVertical: 40, alignItems: 'center' },
    card: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: Colors.border,
      backgroundColor: Colors.card,
      marginBottom: 12,
      overflow: 'hidden',
    },
    cardDone: {
      borderColor: Colors.success + '55',
      backgroundColor: Colors.success + '0d',
    },
    cardHeader: { padding: 14 },
    cardHeaderTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      marginBottom: 4,
    },
    cardTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, flex: 1 },
    cardTitle: { fontSize: 15, fontWeight: '700', color: Colors.text, flexShrink: 1 },
    cardTitleDone: { color: Colors.successDark },
    statusBadge: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
    },
    statusBadgeText: { fontSize: 9, fontWeight: '800', color: '#fff', textTransform: 'uppercase' },
    cardBodyPreview: { fontSize: 12, color: Colors.textMuted, fontStyle: 'italic' },
    cardFooter: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 10,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: Colors.border,
    },
    cardFooterId: { fontSize: 10, fontWeight: '700', color: Colors.textMuted, textTransform: 'uppercase' },
    cardFooterToggle: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    cardFooterToggleText: { fontSize: 10, fontWeight: '800', color: Colors.primary, textTransform: 'uppercase' },
    expanded: {
      padding: 14,
      borderTopWidth: 1,
      borderTopColor: Colors.border,
      backgroundColor: Colors.background,
    },
    messageBubbleRow: { marginBottom: 10 },
    messageBubbleRowUser: { alignItems: 'flex-start' },
    messageBubbleRowSupport: { alignItems: 'flex-end' },
    bubble: {
      maxWidth: '90%',
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 8,
    },
    bubbleUser: {
      backgroundColor: Colors.card,
      borderWidth: 1,
      borderColor: Colors.border,
      borderTopLeftRadius: 2,
    },
    bubbleSupport: {
      backgroundColor: Colors.primary,
      borderTopRightRadius: 2,
    },
    bubbleText: { fontSize: 12 },
    bubbleTextUser: { color: Colors.text },
    bubbleTextSupport: { color: '#fff' },
    bubbleMeta: {
      fontSize: 9,
      fontWeight: '700',
      color: Colors.textMuted,
      textTransform: 'uppercase',
      marginTop: 4,
      paddingHorizontal: 2,
    },
    resolvedBanner: {
      marginTop: 4,
      marginBottom: 10,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: Colors.success + '18',
    },
    resolvedBannerText: {
      textAlign: 'center',
      fontSize: 10,
      fontWeight: '800',
      color: Colors.successDark,
      textTransform: 'uppercase',
    },
    replyRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 4,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: Colors.border,
    },
    replyInput: {
      flex: 1,
      backgroundColor: Colors.card,
      borderWidth: 1,
      borderColor: Colors.border,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 13,
      color: Colors.text,
    },
    replySendButton: {
      width: 38,
      height: 38,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: Colors.primary,
    },
    replySendButtonDisabled: { opacity: 0.5 },
  });
}
